# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodctl < Formula
  desc "check and update go modules"
  homepage "https://github.com/ormanli/gomodctl"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Darwin_x86_64.tar.gz"
      sha256 "e33354d3f0894c183f4190ea3f5c28806f718ea20d0b655712b2f7d6922fdfc5"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Darwin_arm64.tar.gz"
      sha256 "cd04bbf2ed520bc92a27a66acad53e77e4717107ce1177648f9aa7b89fa437fe"

      def install
        bin.install "gomodctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Linux_arm64.tar.gz"
      sha256 "98b879ef4ed3e6a4ec8b831b445382e1a909bf1b85d2b091901ead8a7c0d5ede"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Linux_x86_64.tar.gz"
      sha256 "1e12e154b926edf4f2226e8a49272556040b3c8b5c0f80614ab09e5791714156"

      def install
        bin.install "gomodctl"
      end
    end
  end

  test do
    system "#{bin/gomodctl}"
  end
end
