# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodctl < Formula
  desc "check and update go modules"
  homepage "https://github.com/ormanli/gomodctl"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Darwin_x86_64.tar.gz"
      sha256 "68c588bff01f4e5cec55daca612f4d3974b4e4b4ef9d24652eb09856ee34fadb"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Darwin_arm64.tar.gz"
      sha256 "8e545e457f68b724c31e6f558acd9dfad2c6929fd4cbd20edc135ed7c3b04c35"

      def install
        bin.install "gomodctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Linux_arm64.tar.gz"
      sha256 "3275380ae501106401b74ca0ebaabe11f4570d48ff567a2e0a66e574b3b59431"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.1/gomodctl_Linux_x86_64.tar.gz"
      sha256 "d9401e86fd309d18abed558608bfb03e7b57d5158cc42bb558a873a52d4c80d9"

      def install
        bin.install "gomodctl"
      end
    end
  end

  test do
    system "#{bin/gomodctl}"
  end
end
