# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodctl < Formula
  desc "check and update go modules"
  homepage "https://github.com/ormanli/gomodctl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.0/gomodctl_Darwin_arm64.tar.gz"
      sha256 "6bbf83af7788af4428105386b5ed8473c0567cf229ab223727f8dd5949cf5621"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.0/gomodctl_Darwin_x86_64.tar.gz"
      sha256 "039e1e217dd02245c28b11a0fa9fc6b10de3a339e735d2f1ecc7a201fdaa6328"

      def install
        bin.install "gomodctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.0/gomodctl_Linux_arm64.tar.gz"
      sha256 "41b2166baf0c3158d3f6f68a2e9a51070760ef193e756e4319bca99309c6d23e"

      def install
        bin.install "gomodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ormanli/gomodctl/releases/download/v0.1.0/gomodctl_Linux_x86_64.tar.gz"
      sha256 "5ee247703e3d528248f48f7fc51dc719cd2b494601a9bff5899a04b7221ea605"

      def install
        bin.install "gomodctl"
      end
    end
  end

  test do
    system "#{bin/gomodctl}"
  end
end
