name: gomodctl build
on: 
  push:
    branches:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Set up Go (1.17)
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Test & Publish
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        # -s used to enable search in specified directory
        bash <(curl -s https://codecov.io/bash) -s .
        cat coverage.txt
    - name: Build
      run: |        
        make build
